We provide SurvivalContour to show the predicted survival or cumulative incidence function (for competing risks data) over time for a single continuous covariate in the form of a contour plot. The estimate for survival probability is based on the Cox model, random survival forest or other parametric survival models, including the spline model, the generalized Gamma AFT model, the stable generalized Gamma AFT model, the Weibull AFT model, the log-logistic  AFT model, and the log-Normal AFT model. The estimate for cumulative incidence function is based on the Fine and Gray model. For more complex deep neural network based models, such as DeepHit, due to the intricacy of manual tuning, we have not included them in this R Shiny app. Instead, we suggest users check out our easy-to-use R package, [survivalContour](https://github.com/YushuShi/survivalContour).


## Options

After successfully loading the data, the shiny app will ask you to choose the time variable, event indicator variable, and the main continuous covariate for plotting the contour plot. We will ask you to specify the range of time and covariate for plotting the predicted survival or the probability of having the primary event. Users can select their preferred color scheme from a few popular choices, define the name of the continuous variable shown in the plot, and specify if they want to plot the confidence interval for 3D contour plot. Users can also adjust for other covariates but need to provide 1) whether the covariates are continuous; 2) the values on which the contour plot for the predicted survival is based.

## Plot result in R shiny app

After clicking the button “Create Plots”, the R shiny app will automatically produce the colored 2D and 3D contour plots of the predicted survival probability (or probability of having the primary event in competing risks data scenario). It will provide the regression coefficient estimates and p-values for the continuous covariate of interest as well as those adjusted covariates. It will also give the estimated survival or cumulative incidence function at 5 quantiles of the covariate. Due to the current limitation of the underlying packages, we do not provide pointwise 95% confidence interval estimates for competing risks data. Users can download the contour plot and survival (CIF) plots with the plotting information.


